### ISSUE TITLE
Can't skip image that starts with a dash

### ISSUE THREAD

**Issue by ToeBee** [nicolas17/mapillary-cmd#1]
Trying to unblur a sequence containing the image with id `-o7MZn1UX8dnmyzG0LhHBA` but I get the error message `mapillary-blurs.py unblur-seq: error: argument --skip: expected one argument`

I've tried double and single quoting it but it seems to be a no-go.

**Comment by nicolas17** [comment]
Thanks for the report. To make this work you can use an equals sign to separate the option and the image ID: `--skip=-o7MZn1UX8dnmyzG0LhHBA`. I will add it to the documentation.
